services:
  server:
    build: .
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./log:/log

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
